### ISSUE TITLE
origami主题更新问题

### ISSUE THREAD

**Issue by ye21st** [syfxlin/origami#1]
目前使用的origami主题版本是之前的旧版本，我想要更新到最新的版本，那么，我是直接批量覆盖主题文件夹吗？还有，我原有的主题设置还有吗？

**Comment by syfxlin** [comment]
@ye21st  主题一开始就嵌入了更新的脚本，后台可以直接更新，也可以手动更新，只要从Release中下载新版本然后覆盖即可，覆盖的时候确保主题文件夹名是Origami即可。
![image](https://user-images.githubusercontent.com/28844480/52915817-65fd3900-3313-11e9-82bb-dd9e3dcfe251.png)

**Comment by ye21st** [comment]
好的，谢谢。 @syfxlin

**Comment by ye21st** [comment]
@syfxlin 你好，我想问下，现在启动主题，网站 php-frm 占用CPU就满了，换回默认主题就没问题，是那个主题自动更新的问题吗？

**Comment by ye21st** [comment]
@syfxlin 应该是老版本主题哪里有问题，更新最新版，负载过高以及CPU过高就好了。

**Comment by syfxlin** [comment]
@ye21st 感谢反馈，我会检查一下代码_(:з」∠)_
