### ISSUE TITLE
i18n & en-US l10n support

### ISSUE THREAD

**Issue by yechs** [syfxlin/origami#11]
以下为功能建议模板，供参考，可根据个人情况删改。
Title：国际化 与 `en-US` 本地化支持

## 列举你希望增加的功能
增加对英语的国际化支持

## 描述一下功能的细节
可以参考 WordPress Theme Handbook 中的 [Internationalization](https://developer.wordpress.org/themes/functionality/internationalization/) 和 [Localization](https://developer.wordpress.org/apis/handbook/internationalization/localization/) 页面

## 是否有替代方案，若有描述一下替代方案
（略）

## 附图
（略）

> 若您有该功能的解决方案，可以同时将方案贴上来。

如果可以的话，我可以提一个 PR 完成这份工作

**Comment by Eriky-git** [comment]
目录可不可以显示到文章右侧，浮动效果，在左下角看起来不是很顺眼~感谢大佬~

**Comment by yechs** [comment]
> 目录可不可以显示到文章右侧，浮动效果，在左下角看起来不是很顺眼~感谢大佬~

@Eriky-git 我不是原开发者啦2333；可以和 @syfxlin 反馈一下……？或者在 Origami 用户的QQ群里面？

**Comment by syfxlin** [comment]
多国语言支持已经在计划中，输出大部分已经使用了文本域（似乎有小部分还未使用文本域），剩下的工作只需要完善文本域的支持和制作mo po文件。（最近在考试所以要等放假后才有空23333

**Comment by syfxlin** [comment]
@Eriky-git 可以考虑下，原本也是打算把目录放到侧边栏的，只是侧边栏如果放了太多小工具后就不知道把目录放何处23333，所以打算参考Kratos主题的侧边栏设计并加以修改下

**Comment by yechs** [comment]
> 多国语言支持已经在计划中，输出大部分已经使用了文本域（似乎有小部分还未使用文本域），剩下的工作只需要完善文本域的支持和制作mo po文件。（最近在考试所以要等放假后才有空23333

好耶！

**Comment by syfxlin** [comment]
@yechs pot模板文件已制作完成，由于我英语水平极为差劲，所以无法胜任翻译工作＞﹏＜

**Comment by yechs** [comment]
> @yechs pot模板文件已制作完成，由于我英语水平极为差劲，所以无法胜任翻译工作＞﹏＜

我或许可以这两周提个 PR，加入英语的 po 和 mo 文件……？

**Comment by syfxlin** [comment]
> > @yechs pot模板文件已制作完成，由于我英语水平极为差劲，所以无法胜任翻译工作＞﹏＜
> 
> 我或许可以这两周提个 PR，加入英语的 po 和 mo 文件……？

可以，非常感谢！

**Comment by yechs** [comment]
咕咕咕……春节前一定PR……

**Comment by syfxlin** [comment]
@yechs 不急不急，现在Origami主题的用户应该还没有国外的hhhh
