### ISSUE TITLE
特色图像平滑处理[优化]

### ISSUE THREAD

**Issue by Gu-f** [syfxlin/origami#13]
以下为功能建议模板，供参考，可根据个人情况删改。
Title：优化文章特色图像

## 目前的问题
* 如果给一篇文章添加了特色图片，当把鼠标放到文章的特色图片上的时候会有一个微放大的现象，但是微放大的过程中显得有些卡顿，有抖动的现象，如果能更平滑的处理该过程，体验上会更好。

## 描述一下功能的细节
* 平滑处理特色图片的微放大过程。

**Comment by syfxlin** [comment]
@Gu-f Origami 主题大部分都是使用CSS动画，已经没有什么优化空间了，抖动或卡顿只有在设备性能不足的情况下才会出现，我测试是流畅的。
