### ISSUE TITLE
Origami主题5.4.1中报错

### ISSUE THREAD

**Issue by tinysheepyang** [syfxlin/origami#14]
以下为提问模板，供参考，可根据个人情况删改。
Title：在最新版5.4.1中使用该主题报错

## 背景
* 出现问题的起因/背景/环境
* php5.6 WordPress5.4.1

## 现象
我想实现上述效果/目的时，遇到了这样的情况：

* 输入：……
* 触发：……
* 问题：……
Notice: wp_enqueue_script的调用方法不正确。脚本和样式应在wp_enqueue_scripts、admin_enqueue_scripts和login_enqueue_scripts钩子之后再加入加载队列（enqueue）或注册（register）。 请查阅调试WordPress来获取更多信息。 （这个消息是在3.3.0版本添加的。） in /cxldata/www/wordpress/wp-includes/functions.php on line 5168

Notice: wp_enqueue_script的调用方法不正确。脚本和样式应在wp_enqueue_scripts、admin_enqueue_scripts和login_enqueue_scripts钩子之后再加入加载队列（enqueue）或注册（register）。 请查阅调试WordPress来获取更多信息。 （这个消息是在3.3.0版本添加的。） in /cxldata/www/wordpress/wp-includes/functions.php on line 5168

Notice: wp_enqueue_style的调用方法不正确。脚本和样式应在wp_enqueue_scripts、admin_enqueue_scripts和login_enqueue_scripts钩子之后再加入加载队列（enqueue）或注册（register）。 请查阅调试WordPress来获取更多信息。 （这个消息是在3.3.0版本添加的。） in /cxldata/www/wordpress/wp-includes/functions.php on line 5168

Notice: wp_enqueue_script的调用方法不正确。脚本和样式应在wp_enqueue_scripts、admin_enqueue_scripts和login_enqueue_scripts钩子之后再加入加载队列（enqueue）或注册（register）。 请查阅调试WordPress来获取更多信息。 （这个消息是在3.3.0版本添加的。） in /cxldata/www/wordpress/wp-includes/functions.php on line 5168

Notice: wp_enqueue_script的调用方法不正确。脚本和样式应在wp_enqueue_scripts、admin_enqueue_scripts和login_enqueue_scripts钩子之后再加入加载队列（enqueue）或注册（register）。 请查阅调试WordPress来获取更多信息。 （这个消息是在3.3.0版本添加的。） in /cxldata/www/wordpress/wp-includes/functions.php on line 5168

Notice: wp_enqueue_script的调用方法不正确。脚本和样式应在wp_enqueue_scripts、admin_enqueue_scripts和login_enqueue_scripts钩子之后再加入加载队列（enqueue）或注册（register）。 请查阅调试WordPress来获取更多信息。 （这个消息是在3.3.0版本添加的。） in /cxldata/www/wordpress/wp-includes/functions.php on line 5168

Notice: wp_enqueue_style的调用方法不正确。脚本和样式应在wp_enqueue_scripts、admin_enqueue_scripts和login_enqueue_scripts钩子之后再加入加载队列（enqueue）或注册（register）。 请查阅调试WordPress来获取更多信息。 （这个消息是在3.3.0版本添加的。） in /cxldata/www/wordpress/wp-includes/functions.php on line 5168

Notice: wp_enqueue_script的调用方法不正确。脚本和样式应在wp_enqueue_scripts、admin_enqueue_scripts和login_enqueue_scripts钩子之后再加入加载队列（enqueue）或注册（register）。 请查阅调试WordPress来获取更多信息。 （这个消息是在3.3.0版本添加的。） in /cxldata/www/wordpress/wp-includes/functions.php on line 5168

Warning: Cannot modify header information - headers already sent by (output started at /cxldata/www/wordpress/wp-includes/functions.php:5168) in /cxldata/www/wordpress/wp-includes/functions.php on line 6221

Warning: Cannot modify header information - headers already sent by (output started at /cxldata/www/wordpress/wp-includes/functions.php:5168) in /cxldata/www/wordpress/wp-admin/includes/misc.php on line 1259

Warning: Cannot modify header information - headers already sent by (output started at /cxldata/www/wordpress/wp-includes/functions.php:5168) in /cxldata/www/wordpress/wp-admin/admin-header.php on line 9

## 分析
我已经做了以下尝试：

* 尝试 0：
  
  * 参考：(请给出检索到的参考文档链接，注意优先使用官方文档)
  * 判断：
  * 实验：
  * 结论：
* 尝试1：
* ……

## 方案
我推测可以有以下几种解决方案，请问大家哪种思路正确，或有其它思路建议？

> 注意：问题解决后
> 
> 1. 你需更新提问内容，在问题最下方补充可用的解决方案，以便后来的同伴参考
> 2. 顺手点击 Issue 下方右下角 close issue ，归档

**Comment by syfxlin** [comment]
请使用 `PHP7.0` 及以上版本，现主题不再对旧版本适配兼容，任何低版本导致的 Bug 不会再进行修复。

**Comment by tinysheepyang** [comment]
谢谢


 原始邮件 
发件人: Otstar Lin<notifications@github.com>
收件人: syfxlin/origami<origami@noreply.github.com>
抄送: tinysheepyang<chen_shiyangnihao@163.com>; Author<author@noreply.github.com>
发送时间: 2020年5月3日(周日) 17:30
主题: Re: [syfxlin/origami] Origami主题5.4.1中报错 (#14)


请使用 PHP7.0 及以上版本，现主题不再对旧版本适配兼容，任何低版本导致的 Bug 不会再进行修复。

**Comment by tinysheepyang** [comment]
PHP 7.1.33 wordpress 5.4.1依然报错
