### ISSUE TITLE
新版本发布计划

### ISSUE THREAD

**Issue by syfxlin** [syfxlin/origami#6]
> Origami Version 2已经开始制作。由于改动的地方非常多，所以新版本不能很快制作完毕，请各位不要着急 （逃。另外，如果您有其他建议或者功能请求，请尽快联系我。

> [Origami演示站](https://origami.ixk.me)已经部署了Origami v2 Beta，开启了大部分功能，使用的是layout3布局，开启了Live Chat，目前Origami v2还未完全完成，若您有更多或更好的想法或功能，请在issue中留言或者发email给我\(￣︶￣*\))，v2预计几天后发布，敬请期待。

## Version 2.0.0 预计包含以下更改
- [x] 去除 jQuery依赖
- [x] REST API搜索
- [x] REST API评论(发表，指定时间内评论者可更新或删除评论)
- [x] 更棒的动画效果
- [x] Origami-image块
- [x] 更换时间轴页面
- [x] 修复TOC滚动不正确的情况
- [x] Sidebar左置
- [x] 首页大图自动切换(幻灯片)
- [x] 将自定义设置移动到普通菜单
- [x] 添加在https下不加载http资源的设置
- [x] 修复评论成功后信息错误问题
- [x] 更换lazyload
- [x] Layout2(无大图布局)
- [x] Layout3(介于Layout2和Layout1中的一种布局)
- [x] 侧栏展示作者卡片
- [x] Markdown区块(支持补全/预览，基于ace编辑器，具体功能请移步[xkeditor](https://xkeditor.ixk.me/))
- [x] 代码高亮区块(支持补全，基于ace编辑器)
- [x] 评论支持Markdown
- [x] 流程图，时序图，甘特图，科学公式(Katex)
- [x] 实时聊天(Live Chat)
- [x] 背景图
- [x] 灵感页面
- [x] 重构友情链接模板
- [x] 移动端适配
- [x] 添加主题静态资源入口，使设置CDN不再痛苦
- [x] 优化加载
- [x] 通知邮件模板
- [x] 前端调节主题风格(背景图，首页图等，并记录)

......

若您有更多或更好的想法或功能，希望将其添加到Origami主题的，请在此issue下方留言。

> 若您熟悉JavaScript，CSS或者PHP并且有意向协助我开发Origami主题，欢迎联系我或在此 issue 下留言。  

## 部分渲染图
![image](https://user-images.githubusercontent.com/28844480/63112474-e0f19480-bfc2-11e9-8cf7-c4edf47d18eb.png)
![image](https://user-images.githubusercontent.com/28844480/63112488-eea71a00-bfc2-11e9-85c9-cdde0cda9045.png)
![image](https://user-images.githubusercontent.com/28844480/63112403-bdc6e500-bfc2-11e9-9cce-5f7f84b13c98.png)
![image](https://user-images.githubusercontent.com/28844480/63112733-8ad12100-bfc3-11e9-831d-b795a1bf29e0.png)
![image](https://user-images.githubusercontent.com/28844480/63112991-2cf10900-bfc4-11e9-9ea8-be5c2501f66d.png)
![image](https://user-images.githubusercontent.com/28844480/63113019-3c705200-bfc4-11e9-99ff-0866e98b97c3.png)
![image](https://user-images.githubusercontent.com/28844480/63113049-498d4100-bfc4-11e9-9f98-bb8b14d6a71b.png)

**Comment by lcxy1** [comment]
希望首页大图可以设置为不显示，或者替换为显示几张幻灯片的效果。希望可以设置边栏左侧显示。

**Comment by WangShuaiHefei** [comment]
希望在博客主页面，可以按照文章的自行设定的  More 标志 ，来展示文章缩略。谢谢

**Comment by jovensun** [comment]
> 希望首页大图可以设置为不显示，或者替换为显示几张幻灯片的效果。希望可以设置边栏左侧显示。

+1。希望首页大图可以设置为不显示。

**Comment by syfxlin** [comment]
Origami v2现已发布，可以通过WordPress后台直接升级，升级后请重新设置下选项。
